# Generated by Django 6.0.6 on 2026-06-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclusion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('complete', 'Complete'), ('not_needed', 'No Longer Needed')], default='incomplete', max_length=20),
        ),
    ]
