# Generated by Django 6.0.6 on 2026-06-21 15:24

import django.db.models.deletion
from django.db import migrations, models


def reshape_referral_categories(apps, schema_editor):
    ReferralCategory = apps.get_model('inclusion', 'ReferralCategory')
    ReferralQuestion = apps.get_model('inclusion', 'ReferralQuestion')

    concern_category = ReferralCategory.objects.filter(name='About the Concern').first()
    if concern_category:
        concern_category.name = 'Concern'
        concern_category.save()
    else:
        concern_category = ReferralCategory.objects.filter(name='Concern').first()
        if not concern_category:
            concern_category = ReferralCategory.objects.create(name='Concern', order=0)

    old_concerns_question = concern_category.questions.filter(label='Concerns').first()
    if old_concerns_question:
        old_concerns_question.label = 'Concern'
        old_concerns_question.order = 0
        old_concerns_question.save()

    existing_labels = set(
        concern_category.questions.filter(label__in=['Concern', 'Concern Details']).values_list('label', flat=True)
    )
    if 'Concern' not in existing_labels:
        ReferralQuestion.objects.create(category=concern_category, label='Concern', order=0)
    if 'Concern Details' not in existing_labels:
        ReferralQuestion.objects.create(category=concern_category, label='Concern Details', order=1)

    flat_categories = ReferralCategory.objects.filter(name__in=['Voice & Views', 'Support So Far'])
    ReferralQuestion.objects.filter(category__in=flat_categories).update(category=None)
    flat_categories.update(is_active=False)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inclusion', '0003_panel_started_at_panelreferral_discussion_started_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralquestion',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='inclusion.referralcategory'),
        ),
        migrations.RunPython(reshape_referral_categories, noop),
    ]
