# Generated by Django 6.0.6 on 2026-06-21 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclusion', '0004_alter_referralquestion_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralquestion',
            name='choices',
            field=models.CharField(blank=True, help_text='Comma-separated options, used when type is Dropdown.', max_length=500),
        ),
        migrations.AddField(
            model_name='referralquestion',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text'), ('select', 'Dropdown')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='action',
            name='status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('complete', 'Complete'), ('not_needed', 'Inactive')], default='incomplete', max_length=20),
        ),
    ]
