# Generated by Django 6.0.6 on 2026-06-21 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclusion', '0005_referralquestion_choices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actioncategory',
            name='is_sensitive',
            field=models.BooleanField(default=False),
        ),
    ]
