# Generated by Django 5.2.15 on 2026-06-22 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_school_staff_school_student_school'),
        ('inclusion', '0006_actioncategory_is_sensitive'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelgroup',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panel_groups', to='core.school'),
        ),
    ]
