# Generated by Django 6.0.6 on 2026-06-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclusion', '0008_expertise_remove_panelgroupmember_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
