# Generated by Django 6.0.6 on 2026-06-22 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_school_staff_school_student_school'),
        ('inclusion', '0009_panel_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panelmember',
            name='role',
        ),
        migrations.AddField(
            model_name='panelmember',
            name='expertise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inclusion.expertise'),
        ),
        migrations.AddField(
            model_name='panelmember',
            name='guest_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='panelmember',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.staff'),
        ),
    ]
