# Generated by Django 5.2.15 on 2026-06-23 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_staff_is_mat_staff'),
        ('inclusion', '0010_remove_panelmember_role_panelmember_expertise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelgroupmember',
            name='guest_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='panelgroupmember',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.staff'),
        ),
    ]
