# Generated by Django 6.0.6 on 2026-06-27 08:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclusion', '0014_rename_primary_concern_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelgroupmember',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='panelmember',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
