# Generated by Django 6.0.6 on 2026-06-28 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_drop_indigo_accent_colour'),
        ('inclusion', '0016_merge_senco_into_send'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('job_title', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='expertise',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expertise_tags', to='core.school'),
        ),
        migrations.AlterUniqueTogether(
            name='panelgroupmember',
            unique_together={('panel_group', 'staff')},
        ),
        migrations.AlterUniqueTogether(
            name='panelmember',
            unique_together={('panel', 'staff')},
        ),
        migrations.AddField(
            model_name='panelgroupmember',
            name='external_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inclusion.externalcontact'),
        ),
        migrations.AddField(
            model_name='panelmember',
            name='external_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inclusion.externalcontact'),
        ),
        migrations.AlterUniqueTogether(
            name='panelgroupmember',
            unique_together={('panel_group', 'external_contact'), ('panel_group', 'staff')},
        ),
        migrations.AlterUniqueTogether(
            name='panelmember',
            unique_together={('panel', 'external_contact'), ('panel', 'staff')},
        ),
        migrations.RemoveField(
            model_name='panelgroupmember',
            name='guest_name',
        ),
        migrations.RemoveField(
            model_name='panelmember',
            name='guest_name',
        ),
    ]
