# Generated by Django 6.0.6 on 2026-06-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclusion', '0017_externalcontact_expertise_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelmember',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='panelmember',
            name='left_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
