# Generated by Django 6.0.6 on 2026-06-28 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_drop_indigo_accent_colour'),
        ('inclusion', '0018_panelmember_checked_in_at_panelmember_left_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panelreferral',
            name='notes',
        ),
        migrations.CreateModel(
            name='PanelReferralNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff')),
                ('panel_referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='inclusion.panelreferral')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
