# Generated by Django 6.0.6 on 2026-06-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='attendance_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='behaviour_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_arrival',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='exclusions_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='is_eal',
            field=models.BooleanField(default=False, verbose_name='EAL'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_lac',
            field=models.BooleanField(default=False, verbose_name='Looked After Child'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_pp',
            field=models.BooleanField(default=False, verbose_name='Pupil Premium'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_young_carer',
            field=models.BooleanField(default=False, verbose_name='Young Carer'),
        ),
        migrations.AddField(
            model_name='student',
            name='sen_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='year_arrived',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
