# Generated by Django 5.2.15 on 2026-06-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_school_staff_school_student_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_mat_staff',
            field=models.BooleanField(default=False),
        ),
    ]
