# Generated by Django 5.2.15 on 2026-06-24 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_staff_is_mat_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary')], max_length=20, unique=True)),
                ('student_term', models.CharField(blank=True, max_length=30)),
                ('staff_term', models.CharField(blank=True, max_length=30)),
                ('portal_title', models.CharField(blank=True, max_length=100)),
                ('accent_colour', models.CharField(blank=True, choices=[('purple', 'Royal Purple'), ('indigo', 'Midnight Indigo'), ('blue', 'Ocean Blue'), ('teal', 'Deep Teal'), ('green', 'Forest Green'), ('yellow', 'Golden Yellow'), ('orange', 'Sunset Orange'), ('burnt', 'Burnt Red'), ('red', 'Cherry Red'), ('pink', 'Blossom Pink')], max_length=10)),
                ('logo_url', models.CharField(blank=True, max_length=300)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('support_phone', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Category settings',
            },
        ),
        migrations.CreateModel(
            name='MatSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_term', models.CharField(blank=True, max_length=30)),
                ('staff_term', models.CharField(blank=True, max_length=30)),
                ('portal_title', models.CharField(blank=True, max_length=100)),
                ('accent_colour', models.CharField(blank=True, choices=[('purple', 'Royal Purple'), ('indigo', 'Midnight Indigo'), ('blue', 'Ocean Blue'), ('teal', 'Deep Teal'), ('green', 'Forest Green'), ('yellow', 'Golden Yellow'), ('orange', 'Sunset Orange'), ('burnt', 'Burnt Red'), ('red', 'Cherry Red'), ('pink', 'Blossom Pink')], max_length=10)),
                ('logo_url', models.CharField(blank=True, max_length=300)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('support_phone', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name': 'MAT settings',
                'verbose_name_plural': 'MAT settings',
            },
        ),
        migrations.AddField(
            model_name='school',
            name='accent_colour',
            field=models.CharField(blank=True, choices=[('purple', 'Royal Purple'), ('indigo', 'Midnight Indigo'), ('blue', 'Ocean Blue'), ('teal', 'Deep Teal'), ('green', 'Forest Green'), ('yellow', 'Golden Yellow'), ('orange', 'Sunset Orange'), ('burnt', 'Burnt Red'), ('red', 'Cherry Red'), ('pink', 'Blossom Pink')], max_length=10),
        ),
        migrations.AddField(
            model_name='school',
            name='logo_url',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='school',
            name='portal_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='staff_term',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='school',
            name='student_term',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='school',
            name='support_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='school',
            name='support_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='staff',
            name='is_developer',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('hidden', 'Hidden'), ('pilot', 'Pilot'), ('live', 'Live')], default='hidden', max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.module')),
                ('pilot_schools', models.ManyToManyField(blank=True, related_name='piloting_modules', to='core.school')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
