# Generated by Django 5.2.15 on 2026-06-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_categorysettings_matsettings_school_accent_colour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='send_need',
            field=models.CharField(blank=True, choices=[('cognition', 'Cognition and Learning'), ('semh', 'Social, Emotional and Mental Health'), ('communication', 'Communication and Interaction'), ('sensory', 'Sensory and/or Physical')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='sen_status',
            field=models.CharField(blank=True, choices=[('K', 'SEN Support (K)'), ('E', 'EHCP (E)')], max_length=1),
        ),
    ]
