# Generated by Django 5.2.15 on 2026-06-25 12:46

from django.db import migrations, models


def remap_burnt_to_orange(apps, schema_editor):
    # "Burnt Red" was dropped as a duplicate of "Sunset Orange" — fold any
    # existing selections into orange rather than leaving an invalid value.
    for model_name in ('School', 'MatSettings', 'CategorySettings'):
        model = apps.get_model('core', model_name)
        model.objects.filter(accent_colour='burnt').update(accent_colour='orange')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_staff_photo'),
    ]

    operations = [
        migrations.RunPython(remap_burnt_to_orange, noop),
        migrations.AlterField(
            model_name='categorysettings',
            name='accent_colour',
            field=models.CharField(blank=True, choices=[('purple', 'Royal Purple'), ('indigo', 'Midnight Indigo'), ('blue', 'Ocean Blue'), ('teal', 'Deep Teal'), ('green', 'Forest Green'), ('yellow', 'Golden Yellow'), ('orange', 'Sunset Orange'), ('red', 'Cherry Red'), ('pink', 'Blossom Pink')], max_length=10),
        ),
        migrations.AlterField(
            model_name='matsettings',
            name='accent_colour',
            field=models.CharField(blank=True, choices=[('purple', 'Royal Purple'), ('indigo', 'Midnight Indigo'), ('blue', 'Ocean Blue'), ('teal', 'Deep Teal'), ('green', 'Forest Green'), ('yellow', 'Golden Yellow'), ('orange', 'Sunset Orange'), ('red', 'Cherry Red'), ('pink', 'Blossom Pink')], max_length=10),
        ),
        migrations.AlterField(
            model_name='school',
            name='accent_colour',
            field=models.CharField(blank=True, choices=[('purple', 'Royal Purple'), ('indigo', 'Midnight Indigo'), ('blue', 'Ocean Blue'), ('teal', 'Deep Teal'), ('green', 'Forest Green'), ('yellow', 'Golden Yellow'), ('orange', 'Sunset Orange'), ('red', 'Cherry Red'), ('pink', 'Blossom Pink')], max_length=10),
        ),
    ]
