# Generated by Django 5.2.15 on 2026-06-25 13:09

from django.db import migrations, models


def remap_indigo_to_purple(apps, schema_editor):
    # "Midnight Indigo" was dropped to bring the accent count to an even 8 —
    # fold any existing selections into its nearest neighbour, purple.
    for model_name in ('School', 'MatSettings', 'CategorySettings'):
        model = apps.get_model('core', model_name)
        model.objects.filter(accent_colour='indigo').update(accent_colour='purple')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_drop_burnt_accent_colour'),
    ]

    operations = [
        migrations.RunPython(remap_indigo_to_purple, noop),
        migrations.AlterField(
            model_name='categorysettings',
            name='accent_colour',
            field=models.CharField(blank=True, choices=[('purple', 'Royal Purple'), ('blue', 'Ocean Blue'), ('teal', 'Deep Teal'), ('green', 'Forest Green'), ('yellow', 'Golden Yellow'), ('orange', 'Sunset Orange'), ('red', 'Cherry Red'), ('pink', 'Blossom Pink')], max_length=10),
        ),
        migrations.AlterField(
            model_name='matsettings',
            name='accent_colour',
            field=models.CharField(blank=True, choices=[('purple', 'Royal Purple'), ('blue', 'Ocean Blue'), ('teal', 'Deep Teal'), ('green', 'Forest Green'), ('yellow', 'Golden Yellow'), ('orange', 'Sunset Orange'), ('red', 'Cherry Red'), ('pink', 'Blossom Pink')], max_length=10),
        ),
        migrations.AlterField(
            model_name='school',
            name='accent_colour',
            field=models.CharField(blank=True, choices=[('purple', 'Royal Purple'), ('blue', 'Ocean Blue'), ('teal', 'Deep Teal'), ('green', 'Forest Green'), ('yellow', 'Golden Yellow'), ('orange', 'Sunset Orange'), ('red', 'Cherry Red'), ('pink', 'Blossom Pink')], max_length=10),
        ),
    ]
