# Generated by Django 5.2.15 on 2026-07-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_drop_indigo_accent_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ethnicity',
            field=models.CharField(blank=True, choices=[('white_british', 'White British'), ('white_other', 'White Other'), ('mixed', 'Mixed / Multiple Ethnic Groups'), ('asian', 'Asian or Asian British'), ('black', 'Black or Black British'), ('chinese', 'Chinese'), ('other', 'Any Other Ethnic Group')], max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='is_more_able',
            field=models.BooleanField(default=False, verbose_name='More Able'),
        ),
        migrations.AddField(
            model_name='student',
            name='prior_attainment_band',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('middle', 'Middle'), ('high', 'High')], max_length=10),
        ),
    ]
