# Generated by Django 6.0.6 on 2026-07-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='house',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
