# Generated by Django 6.0.6 on 2026-07-15 12:37

import datetime

import django.db.models.deletion
from django.db import migrations, models


def _year_for_date(AcademicYear, d):
    # Mirrors AcademicYear.for_date() on the real model - migrations use
    # historical models (apps.get_model), which only carry fields, not
    # custom methods, so the resolution logic is duplicated here rather
    # than imported. Keep in sync with core.models.AcademicYear.for_date.
    year = AcademicYear.objects.filter(start_date__lte=d).order_by('-start_date').first()
    if year:
        return year
    start_year = d.year if d.month >= 9 else d.year - 1
    year, _ = AcademicYear.objects.get_or_create(
        start_date=datetime.date(start_year, 9, 1),
        defaults={'end_date': datetime.date(start_year + 1, 8, 31)},
    )
    return year


def backfill_academic_year(apps, schema_editor):
    Referral = apps.get_model('core', 'Referral')
    AcademicYear = apps.get_model('core', 'AcademicYear')
    for referral in Referral.objects.filter(academic_year__isnull=True):
        referral.academic_year = _year_for_date(AcademicYear, referral.created_at.date())
        referral.save(update_fields=['academic_year'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_academicyear_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='academic_year',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='core.academicyear'),
        ),
        migrations.RunPython(backfill_academic_year, noop),
    ]
