# Generated by Django 6.0.6 on 2026-07-15 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_staffgroup_staffgroupmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='attendance_pct',
        ),
        migrations.RemoveField(
            model_name='student',
            name='behaviour_summary',
        ),
        migrations.RemoveField(
            model_name='student',
            name='exclusions_count',
        ),
        migrations.CreateModel(
            name='BehaviourIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('disruption', 'Disruption'), ('aggression', 'Aggression'), ('defiance', 'Defiance'), ('other', 'Other')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviour_incidents', to='core.student')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Exclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(choices=[('fixed_term', 'Fixed-term'), ('permanent', 'Permanent'), ('internal', 'Internal')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusions', to='core.student')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('am_status', models.CharField(choices=[('present', 'Present'), ('absent_unauthorised', 'Absent (Unauthorised)'), ('absent_authorised', 'Absent (Authorised)'), ('late', 'Late')], default='present', max_length=20)),
                ('pm_status', models.CharField(choices=[('present', 'Present'), ('absent_unauthorised', 'Absent (Unauthorised)'), ('absent_authorised', 'Absent (Authorised)'), ('late', 'Late')], default='present', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_days', to='core.student')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
