# Generated by Django 6.0.6 on 2026-07-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_student_attendance_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_dsl',
            field=models.BooleanField(default=False),
        ),
    ]
