# Generated by Django 6.0.6 on 2026-07-16 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_staff_is_dsl'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafeguardingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('retirement_reason', models.CharField(blank=True, choices=[('superseded', 'Superseded by a newer note'), ('resolved', 'Resolved'), ('no_longer_relevant', 'No longer relevant'), ('entered_in_error', 'Entered in error')], max_length=20)),
                ('retirement_note', models.TextField(blank=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.staff')),
                ('retired_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safeguarding_notes', to='core.student')),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='core.safeguardingnote')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
