# Generated by Django 6.0.6 on 2026-07-16 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_safeguardingnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='safeguardingnote',
            name='reactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='safeguardingnote',
            name='reactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.staff'),
        ),
    ]
