# Generated by Django 6.0.6 on 2026-07-22 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_safeguardingnote_reactivated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositiveBehaviourIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('merit', 'Merit'), ('effort', 'Effort'), ('achievement', 'Achievement'), ('kindness', 'Kindness'), ('other', 'Other')], max_length=20)),
                ('points', models.PositiveIntegerField(default=1)),
                ('logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positive_behaviour_incidents', to='core.student')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
