# Generated by Django 6.0.6 on 2026-08-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_positivebehaviourincident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sen_status',
            field=models.CharField(blank=True, choices=[('K', 'K'), ('E', 'E')], max_length=1),
        ),
    ]
