# Generated by Django 5.2.15 on 2026-08-25 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_student_sen_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='core.staff')),
            ],
            options={
                'indexes': [models.Index(fields=['staff', 'url_name', 'created_at'], name='core_pagevi_staff_i_c71b22_idx')],
            },
        ),
    ]
