# Generated by Django 6.0.6 on 2026-09-13 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_student_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='safeguarding_notes_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SafeguardingReadinessConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('notes_version', models.PositiveIntegerField()),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safeguarding_readiness_confirmations', to='core.student')),
            ],
            options={
                'ordering': ['-confirmed_at', '-id'],
            },
        ),
    ]
