# Generated by Django 5.2.15 on 2026-07-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_inclusionreferral_referral_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='panel',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='panelreferral',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
