# Generated by Django 5.2.15 on 2026-07-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_action_completed_at_panel_ended_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('complete', 'Complete'), ('not_needed', 'Not Required')], default='incomplete', max_length=20),
        ),
    ]
