# Generated by Django 5.2.15 on 2026-07-03 14:15

from django.db import migrations, models


def migrate_upcoming_status(apps, schema_editor):
    Panel = apps.get_model('panel', 'Panel')
    upcoming = Panel.objects.filter(status='upcoming')
    upcoming.filter(started_at__isnull=False, ended_at__isnull=True).update(status='running')
    upcoming.exclude(started_at__isnull=False, ended_at__isnull=True).update(status='draft')


def reverse_upcoming_status(apps, schema_editor):
    Panel = apps.get_model('panel', 'Panel')
    Panel.objects.filter(status__in=['draft', 'ready', 'delayed', 'running']).update(status='upcoming')


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_alter_action_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('running', 'Running'), ('delayed', 'Delayed'), ('complete', 'Complete')], default='draft', max_length=20),
        ),
        migrations.RunPython(migrate_upcoming_status, reverse_upcoming_status),
    ]
