# Generated by Django 5.2.15 on 2026-07-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_alter_panel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelreferral',
            name='agenda_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
