# Generated by Django 6.0.6 on 2026-07-09 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0013_remove_panelreferral_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='origin_panel_referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_actions', to='panel.panelreferral'),
        ),
    ]
