# Generated by Django 6.0.6 on 2026-07-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0014_action_origin_panel_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inclusionreferral',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('review_scheduled', 'Review Scheduled'), ('awaiting_review', 'Awaiting Review'), ('closed', 'Closed')], default='open', max_length=20),
        ),
    ]
