# Generated by Django 6.0.6 on 2026-07-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0016_alter_inclusionreferral_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelgroupmember',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='panelgroupmember',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
