# Generated by Django 6.0.6 on 2026-07-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0020_backfill_panelmember_checked_in_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='chair_follows_default',
            field=models.BooleanField(default=False),
        ),
    ]
