# Generated by Django 6.0.6 on 2026-07-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0022_action_created_at_action_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='auto_ended',
            field=models.BooleanField(default=False),
        ),
    ]
