# Generated by Django 6.0.6 on 2026-07-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0023_panel_auto_ended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelreferral',
            name='discussion_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('discussed', 'Discussed'), ('deferred', 'Deferred')], default='pending', max_length=20),
        ),
    ]
