# Generated by Django 6.0.6 on 2026-07-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0024_alter_panelreferral_discussion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelreferral',
            name='discussion_auto_stopped',
            field=models.BooleanField(default=False),
        ),
    ]
