# Generated by Django 6.0.6 on 2026-07-15 12:37

import datetime

import django.db.models.deletion
from django.db import migrations, models


def _year_for_date(AcademicYear, d):
    # Mirrors AcademicYear.for_date() on the real model - see the identical
    # helper (and why it's duplicated) in core/migrations/0015_referral_
    # academic_year.py.
    year = AcademicYear.objects.filter(start_date__lte=d).order_by('-start_date').first()
    if year:
        return year
    start_year = d.year if d.month >= 9 else d.year - 1
    year, _ = AcademicYear.objects.get_or_create(
        start_date=datetime.date(start_year, 9, 1),
        defaults={'end_date': datetime.date(start_year + 1, 8, 31)},
    )
    return year


def backfill_academic_year(apps, schema_editor):
    Panel = apps.get_model('panel', 'Panel')
    Action = apps.get_model('panel', 'Action')
    AcademicYear = apps.get_model('core', 'AcademicYear')

    for panel in Panel.objects.filter(academic_year__isnull=True):
        panel.academic_year = _year_for_date(AcademicYear, panel.date)
        panel.save(update_fields=['academic_year'])

    # created_at is null on Actions that predate the field (see its own
    # comment in models.py) - nothing to backfill from for those, they stay
    # academic_year=None.
    for action in Action.objects.filter(academic_year__isnull=True, created_at__isnull=False):
        action.academic_year = _year_for_date(AcademicYear, action.created_at.date())
        action.save(update_fields=['academic_year'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_referral_academic_year'),
        ('panel', '0025_panelreferral_discussion_auto_stopped'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='academic_year',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='core.academicyear'),
        ),
        migrations.AddField(
            model_name='panel',
            name='academic_year',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panels', to='core.academicyear'),
        ),
        migrations.RunPython(backfill_academic_year, noop),
    ]
