# Generated by Django 6.0.6 on 2026-07-15 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0026_action_academic_year_panel_academic_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='panelreferralnote',
            options={'ordering': ['created_at']},
        ),
    ]
