# Generated by Django 6.0.6 on 2026-07-15 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_staffgroup_staffgroupmember'),
        ('panel', '0027_alter_panelreferralnote_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='assigned_to_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.staffgroup'),
        ),
    ]
