# Generated by Django 6.0.6 on 2026-07-16 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_staff_is_dsl'),
        ('panel', '0028_action_assigned_to_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafeguardingBriefing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff')),
                ('panel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safeguarding_briefings', to='panel.panel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safeguarding_briefings', to='core.student')),
            ],
            options={
                'db_table': 'inclusion_safeguardingbriefing',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='StudentNote',
        ),
    ]
