# Generated by Django 6.0.6 on 2026-07-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0029_safeguardingbriefing_delete_studentnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelreferral',
            name='briefing_ready',
            field=models.BooleanField(default=False),
        ),
    ]
