# Generated by Django 6.0.6 on 2026-07-16 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0030_panelreferral_briefing_ready'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SafeguardingBriefing',
        ),
    ]
