# Generated by Django 6.0.6 on 2026-07-25 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0031_delete_safeguardingbriefing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('running', 'Running'), ('delayed', 'Delayed'), ('complete', 'Complete'), ('void', 'Void')], default='draft', max_length=20),
        ),
    ]
