# Generated by Django 6.0.6 on 2026-07-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0032_alter_panel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelreferral',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
