# Generated by Django 6.0.6 on 2026-07-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0033_panelreferral_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='last_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
