# Generated by Django 6.0.6 on 2026-07-25 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0034_panel_last_confirmed_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='assigned_to',
            new_name='assigned_to_staff',
        ),
    ]
