# Generated by Django 6.0.6 on 2026-09-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0036_alter_inclusionreferral_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inclusionreferral',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('review_scheduled', 'Review Scheduled'), ('awaiting_review', 'Awaiting Review'), ('overdue_review', 'Overdue'), ('assigned', 'Assigned'), ('discussing', 'Discussing'), ('closed', 'Closed')], default='open', max_length=20),
        ),
    ]
