# Generated by Django 6.0.6 on 2026-09-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_student_photo'),
        ('panel', '0037_alter_inclusionreferral_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelgroup',
            name='is_mat_wide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='escalation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('referral',), name='unique_open_escalation_per_referral'),
        ),
        migrations.AddConstraint(
            model_name='panelgroup',
            constraint=models.UniqueConstraint(condition=models.Q(('is_mat_wide', True)), fields=('is_mat_wide',), name='unique_mat_wide_panel_group'),
        ),
    ]
