# Generated by Django 6.0.6 on 2026-09-12 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_student_photo'),
        ('panel', '0038_panelgroup_is_mat_wide_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelReferralRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='panel_recordings/%Y/%m/%d/')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('panel_referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='panel.panelreferral')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff')),
            ],
            options={
                'db_table': 'inclusion_panelreferralrecording',
                'ordering': ['created_at'],
            },
        ),
    ]
