# Generated by Django 6.0.6 on 2026-09-13 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0039_panelreferralrecording'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panelreferral',
            name='briefing_ready',
        ),
    ]
