# Generated by Django 6.0.6 on 2026-09-14 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0040_remove_panelreferral_briefing_ready'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='note',
            new_name='description',
        ),
    ]
