# Generated by Django 6.0.6 on 2026-09-14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_student_safeguarding_notes_version_and_more'),
        ('panel', '0041_rename_note_action_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escalation',
            name='resolution_notes',
        ),
        migrations.AddField(
            model_name='escalation',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.staff'),
        ),
    ]
