# Generated by Django 6.0.6 on 2026-09-14 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_student_safeguarding_notes_version_and_more'),
        ('panel', '0042_escalation_resolved_by_drop_resolution_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='panel.action')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.staff')),
            ],
            options={
                'db_table': 'inclusion_actionupdate',
                'ordering': ['created_at'],
            },
        ),
    ]
