# Generated by Django 6.0.6 on 2026-09-15 22:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_student_safeguarding_notes_version_and_more'),
        ('panel', '0043_actionupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralPriorityChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_priority', models.CharField(blank=True, default='', max_length=10)),
                ('to_priority', models.CharField(blank=True, default='', max_length=10)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.staff')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priority_changes', to='panel.inclusionreferral')),
            ],
            options={
                'db_table': 'inclusion_referralprioritychange',
                'ordering': ['-changed_at', '-id'],
            },
        ),
    ]
