# Generated by Django 6.0.6 on 2026-09-15 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_student_safeguarding_notes_version_and_more'),
        ('panel', '0043_actionupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresetReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(choices=[('escalation', 'Escalation'), ('member_deactivation', 'Panel Group Member Deactivation')], max_length=30)),
                ('text', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'inclusion_presetreason',
                'ordering': ['context', 'order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='panelgroupmember',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.staff'),
        ),
        migrations.AddField(
            model_name='panelgroupmember',
            name='deactivation_reason',
            field=models.TextField(blank=True),
        ),
    ]
