#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# Every path this wizard writes is relative to the repo root, so anchor there
# rather than trusting the directory the human happened to run from.
REPO_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
cd "$REPO_ROOT"
ENV_FILE="$REPO_ROOT/.env"

VENV_PY="$REPO_ROOT/.venv/Scripts/python.exe"
[[ -x "$VENV_PY" ]] || VENV_PY="$REPO_ROOT/.venv/bin/python"

# The Python extension reads MANAGE_PY_PATH as an OS-native path string, so on
# Windows it wants D:\... and not the /d/... that bash reports.
to_native_path() {
  if command -v cygpath >/dev/null 2>&1; then cygpath -w "$1"; else printf '%s' "$1"; fi
}

banner "VS Code Testing tab: Django tests"

# ── Stage 1 ───────────────────────────────────────────────────────────────
stage "Preflight"
say "Checking this machine has what the Testing tab needs."
printf '\n'

if [[ -f "$REPO_ROOT/manage.py" ]]; then
  say "OK   repo root: $REPO_ROOT"
else
  warn "no manage.py at $REPO_ROOT - run this script from inside the repo."
  exit 1
fi

if [[ -x "$VENV_PY" ]]; then
  say "OK   virtualenv python: $VENV_PY"
else
  warn "no python in .venv. Create it, then install the requirements:"
  note "  python -m venv .venv"
  note "  .venv\\Scripts\\python.exe -m pip install -r requirements.txt"
  exit 1
fi

if "$VENV_PY" -c "import django" >/dev/null 2>&1; then
  say "OK   Django importable in the virtualenv"
else
  warn "Django isn't installed in .venv (CLAUDE.md: .venv ships with only pip)."
  note "  .venv\\Scripts\\python.exe -m pip install -r requirements.txt"
  exit 1
fi

if command -v code >/dev/null 2>&1; then
  say "OK   the 'code' CLI is on PATH, so this wizard can install the extension for you"
  HAVE_CODE_CLI=1
else
  HAVE_CODE_CLI=0
  warn "the 'code' CLI isn't on PATH - you'll install the extension by hand in stage 2."
  note "To add it later: VS Code -> Ctrl+Shift+P -> 'Shell Command: Install code command in PATH'"
fi

printf '\n'
pause "All good. Press Enter for stage 2."

# ── Stage 2 ───────────────────────────────────────────────────────────────
stage "The Python extension"
say "The Testing tab is provided by Microsoft's Python extension (ms-python.python)."
printf '\n'

if [[ "$HAVE_CODE_CLI" == "1" ]] && code --list-extensions 2>/dev/null | grep -qix "ms-python.python"; then
  say "OK   ms-python.python is already installed - nothing to do."
elif [[ "$HAVE_CODE_CLI" == "1" ]]; then
  say "Installing it now..."
  if code --install-extension ms-python.python --force; then
    say "OK   installed"
  else
    SKIPPED+=("install the Python extension (ms-python.python) from the Marketplace")
    warn "install failed - do it by hand from the Extensions view."
  fi
else
  open_url "https://marketplace.visualstudio.com/items?itemName=ms-python.python"
  step "Click Install (or use VS Code's Extensions view and search 'Python')."
  step "Wait for it to finish installing."
  pause "Done? Press Enter."
fi

printf '\n'
pause "Press Enter for stage 3."

# ── Stage 3 ───────────────────────────────────────────────────────────────
stage "Tell the extension where manage.py is"
say "Django tests can't run under plain unittest discovery: they need a test"
say "database and django.setup() first. The Python extension handles that only"
say "when MANAGE_PY_PATH is set, at which point it shells out to manage.py test."
printf '\n'

MANAGE_PY_NATIVE=$(to_native_path "$REPO_ROOT/manage.py")
say "Detected: $MANAGE_PY_NATIVE"
printf '\n'

# Single-quoted so Windows backslashes survive as literal characters, which is
# the form the extension's documentation uses.
write_env MANAGE_PY_PATH "'$MANAGE_PY_NATIVE'"
note ".env is gitignored, so this stays on your machine."

printf '\n'
pause "Press Enter for stage 4."

# ── Stage 4 ───────────────────────────────────────────────────────────────
stage "Write .vscode/settings.json"
say "Turning on unittest discovery and pointing VS Code at .venv and .env."
printf '\n'

VSCODE_SETTINGS="$REPO_ROOT/.vscode/settings.json"
mkdir -p "$REPO_ROOT/.vscode"

WRITE_SETTINGS=1
if [[ -s "$VSCODE_SETTINGS" ]]; then
  warn "$VSCODE_SETTINGS already exists."
  say "Its other keys will be preserved; only the python.* keys below change."
  if confirm "Back it up to settings.json.bak and merge?"; then
    cp "$VSCODE_SETTINGS" "$VSCODE_SETTINGS.bak"
    say "OK   backed up to settings.json.bak"
  else
    WRITE_SETTINGS=0
    SKIPPED+=("write .vscode/settings.json - you declined the merge")
    warn "skipping; the Testing tab won't discover anything without these keys."
  fi
fi

if [[ "$WRITE_SETTINGS" == "1" ]]; then
  # Merging through python rather than a heredoc keeps any hand-added keys, and
  # tolerates the // comments VS Code allows in settings.json.
  "$VENV_PY" "$REPO_ROOT/scripts/_vscode_testing_settings.py" "$VSCODE_SETTINGS"
  note ".vscode/ is gitignored too, so this is per-clone setup - hence this script."
fi

printf '\n'
pause "Press Enter for stage 5."

# ── Stage 5 ───────────────────────────────────────────────────────────────
stage "Reload VS Code and pick the interpreter"
say "VS Code reads .env and settings.json when the window loads, so the window"
say "has to be reloaded before anything from stages 3-4 takes effect."
printf '\n'
step "Switch to VS Code."
step "Ctrl+Shift+P -> 'Developer: Reload Window' -> Enter."
step "Ctrl+Shift+P -> 'Python: Select Interpreter'."
step "Choose the one inside .venv (its path ends in .venv\\Scripts\\python.exe)."
note "If it isn't listed, pick 'Enter interpreter path' and paste:"
note "  $(to_native_path "$VENV_PY")"
printf '\n'
pause "Reloaded and interpreter selected? Press Enter."

# ── Stage 6 ───────────────────────────────────────────────────────────────
stage "Verify discovery"
say "First a baseline from the command line, so that if the Testing tab"
say "disagrees you know the problem is VS Code's wiring and not the tests."
printf '\n'

if confirm "Run the suite now with manage.py test?"; then
  printf '\n'
  "$VENV_PY" manage.py test 2>&1 | tail -n 20 || warn "the suite itself is failing - fix that before blaming the Testing tab."
  printf '\n'
fi

step "In VS Code, click the Testing beaker icon in the left activity bar."
step "Click the refresh icon at the top of the Testing panel to discover tests."
step "You should see core, portal and hubs.inclusion.panel as a test tree."
step "Hit the play icon at the top to run everything."
printf '\n'
note "If the tree is empty, open View -> Output -> 'Python' and read the log."
note "The usual causes: window not reloaded (stage 5), the wrong interpreter"
note "selected, or MANAGE_PY_PATH missing from .env (stage 3)."
printf '\n'

if ! confirm "Did the tests appear in the Testing tab?"; then
  SKIPPED+=("Testing tab discovery - check the Python output log as above")
fi

finish
